name: Node.js CI + Publish

on:
  push:
    branches: [ "main" ]
    # Only publish on version bumps (if package.json version changed)
    paths:
      - 'package.json'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Clone the repo on Ubuntu VM on GitHub  
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check versions
        run: |
          npm -v
          node -v

      - name: Build (if applicable)
        run: npm run build --if-present

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
