name: Node.js CI + Publish

on:
  push:
    branches: [ "main" ]
    # Only publish on version bumps (if package.json version changed)
    paths:
      - 'package.json'

jobs:
  # Job 1  
  build-and-publish:
    runs-on: ubuntu-latest  # This Workflow will run on ubuntu-latest  

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: clone the repo on ubuntu vm on github  
      - uses: actions/checkout@v4
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4   # Install node on that github ubuntu vm  
        with:
          node-version: ${{ matrix.node-version }}   # describe the version  
          registry-url: 'https://registry.npmjs.org/' # give the url  
          cache: 'npm'

      - run: npm ci
      - run: npm -v
      - run: node -v
      - run: npm run build --if-present

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
